"""add_scaled_index_to_Team

Revision ID: 0e2ea833515b
Revises: 5e4fd1fb5413
Create Date: 2025-11-03 10:33:21.327228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2ea833515b'
down_revision: Union[str, Sequence[str], None] = '5e4fd1fb5413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teams', sa.Column('scaledStatIndex', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Teams', 'scaledStatIndex')
    # ### end Alembic commands ###
