"""initial

Revision ID: 193f1ee688f5
Revises: 
Create Date: 2025-11-03 10:09:35.979351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '193f1ee688f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teams')
    op.drop_index(op.f('ml_model_weights_sport'), table_name='MlModelWeights')
    op.drop_table('MlModelWeights')
    op.drop_index(op.f('games_home_team_away_team_commence_time_sport'), table_name='Games')
    op.drop_index(op.f('games_sport_key_complete'), table_name='Games')
    op.drop_table('Games')
    op.drop_table('HyperParams')
    op.drop_table('Sports')
    op.drop_table('SequelizeMeta')
    op.drop_index(op.f('value_bet_settings_sport_bookmaker'), table_name='ValueBetSettings')
    op.drop_table('ValueBetSettings')
    op.drop_table('PastGames')
    op.drop_index(op.f('stats_game_id_team_id'), table_name='Stats')
    op.drop_table('Stats')
    op.drop_index(op.f('markets_bookmaker_id_key'), table_name='Markets')
    op.drop_table('Markets')
    op.drop_index(op.f('bookmakers_game_id_key'), table_name='Bookmakers')
    op.drop_table('Bookmakers')
    op.drop_index(op.f('outcomes_market_id_name'), table_name='Outcomes')
    op.drop_table('Outcomes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Outcomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marketId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teamId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('impliedProbability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['marketId'], ['Markets.id'], name=op.f('Outcomes_marketId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['Teams.id'], name=op.f('Outcomes_teamId_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Outcomes_pkey'))
    )
    op.create_index(op.f('outcomes_market_id_name'), 'Outcomes', ['marketId', 'name'], unique=True)
    op.create_table('Bookmakers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Bookmakers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('gameId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['Games.id'], name='Bookmakers_gameId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], name='Bookmakers_sport_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='Bookmakers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('bookmakers_game_id_key'), 'Bookmakers', ['gameId', 'key'], unique=True)
    op.create_table('Markets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bookmakerId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookmakerId'], ['Bookmakers.id'], name=op.f('Markets_bookmakerId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Markets_pkey'))
    )
    op.create_index(op.f('markets_bookmaker_id_key'), 'Markets', ['bookmakerId', 'key'], unique=True)
    op.create_table('Stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gameId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teamId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sport', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['Games.id'], name=op.f('Stats_gameId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['Teams.id'], name=op.f('Stats_teamId_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Stats_pkey'))
    )
    op.create_index(op.f('stats_game_id_team_id'), 'Stats', ['gameId', 'teamId'], unique=True)
    op.create_table('PastGames',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('homeTeam', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awayTeam', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commence_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('homeTeamIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('awayTeamIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('homeTeamScaledIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('awayTeamScaledIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('winPercent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('predictedWinner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('predictionConfidence', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('homeScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awayScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeRemaining', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bookmakers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('homeStats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awayStats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PastGames_pkey'))
    )
    op.create_table('ValueBetSettings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('indexDiffSmall', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('indexDiffRange', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('confidenceSmall', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('confidenceRange', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('bestWinrate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('bestTotalGames', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('bestConfidenceInterval', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('bookmaker', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bestCIScore', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], name=op.f('ValueBetSettings_sport_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ValueBetSettings_pkey'))
    )
    op.create_index(op.f('value_bet_settings_sport_bookmaker'), 'ValueBetSettings', ['sport', 'bookmaker'], unique=True)
    op.create_table('SequelizeMeta',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('SequelizeMeta_pkey'))
    )
    op.create_table('Sports',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sports_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('espnSport', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('league', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('startMonth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endMonth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('multiYear', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('statYear', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prevStatYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sigmoidIQRSharpness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('averageIndex', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Sports_pkey'),
    sa.UniqueConstraint('name', name='Sports_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('HyperParams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bestAccuracy', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('epochs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('batchSize', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('kFolds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('hiddenLayers', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('learningRate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('l2Reg', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('dropoutReg', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('kernalInitializer', sa.VARCHAR(length=255), server_default=sa.text("'glorotUniform'::character varying"), autoincrement=False, nullable=False),
    sa.Column('layerNeurons', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('decayFactor', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('gameDecayThreshold', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('historyLength', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('scoreMAE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spreadMAE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('totalMAE', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scoreLoss', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('winPctLoss', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.Column('earlyStopPatience', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], name=op.f('HyperParams_sport_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('HyperParams_pkey'))
    )
    op.create_table('Games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oddsApiID', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('homeTeam', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awayTeam', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sport_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sport_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('commence_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('homeTeamIndex', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('awayTeamIndex', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('homeTeamScaledIndex', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('awayTeamScaledIndex', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('winPercent', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('predictedWinner', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('predictionConfidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('homeScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awayScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeRemaining', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predictionCorrect', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('winner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('predictedHomeScore', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('predictedAwayScore', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('probablePitcher', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['awayTeam'], ['Teams.id'], name=op.f('Games_awayTeam_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['homeTeam'], ['Teams.id'], name=op.f('Games_homeTeam_fkey'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], name=op.f('Games_sport_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Games_pkey')),
    sa.UniqueConstraint('oddsApiID', name=op.f('Games_oddsApiID_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('games_sport_key_complete'), 'Games', ['sport_key', 'complete'], unique=False)
    op.create_index(op.f('games_home_team_away_team_commence_time_sport'), 'Games', ['homeTeam', 'awayTeam', 'commence_time', 'sport'], unique=True)
    op.create_table('MlModelWeights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('featureImportanceScores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hiddenToOutputWeights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('inputToHiddenWeights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], name=op.f('MlModelWeights_sport_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('MlModelWeights_pkey'))
    )
    op.create_index(op.f('ml_model_weights_sport'), 'MlModelWeights', ['sport'], unique=True)
    op.create_table('Teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teamName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('league', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('espnID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('espnDisplayName', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mainColor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secondaryColor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('currentStats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('espnLeague', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('statIndex', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('statCategoryIndexes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lightLogo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('darkLogo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pitcherStats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Teams_pkey'))
    )
    # ### end Alembic commands ###
