"""rename_and_add_ML_columns

Revision ID: 291e61c626ae
Revises: 77956cefb786
Create Date: 2025-11-05 10:54:23.073691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291e61c626ae'
down_revision: Union[str, Sequence[str], None] = '77956cefb786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MlModelWeights', sa.Column('featureImportanceScoresTeam', sa.JSON(), nullable=True))
    op.add_column('MlModelWeights', sa.Column('featureImportanceScoresFull', sa.JSON(), nullable=True))
    op.drop_column('MlModelWeights', 'featureImportanceScores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MlModelWeights', sa.Column('featureImportanceScores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('MlModelWeights', 'featureImportanceScoresFull')
    op.drop_column('MlModelWeights', 'featureImportanceScoresTeam')
    # ### end Alembic commands ###
