"""add_cascade_to_bookmaker_delete

Revision ID: 29ab340ce81c
Revises: 4bace791e7ff
Create Date: 2026-01-01 09:07:57.526252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ab340ce81c'
down_revision: Union[str, Sequence[str], None] = '4bace791e7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Bookmakers_gameId_fkey'), 'Bookmakers', type_='foreignkey')
    op.create_foreign_key(None, 'Bookmakers', 'Games', ['gameId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Bookmakers', type_='foreignkey')
    op.create_foreign_key(op.f('Bookmakers_gameId_fkey'), 'Bookmakers', 'Games', ['gameId'], ['id'])
    # ### end Alembic commands ###
