"""tables check

Revision ID: 39d2278f2458
Revises: 90ada5bcdcd6
Create Date: 2025-11-03 10:29:19.288931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d2278f2458'
down_revision: Union[str, Sequence[str], None] = '90ada5bcdcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('prevStatYear', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'prevStatYear')
    # ### end Alembic commands ###
