"""new_hyperparam_columns

Revision ID: 4097de6fe2be
Revises: f0d9f3a84f03
Create Date: 2025-11-22 22:04:13.155004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4097de6fe2be'
down_revision: Union[str, Sequence[str], None] = 'f0d9f3a84f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HyperParams', sa.Column('regression_min_child_weight', sa.Integer(), nullable=True))
    op.add_column('HyperParams', sa.Column('classification_min_child_weight', sa.Integer(), nullable=True))
    op.drop_column('HyperParams', 'classification_colsample_bylevel')
    op.drop_column('HyperParams', 'regression_early_stopping_rounds')
    op.drop_column('HyperParams', 'regression_colsample_bylevel')
    op.drop_column('HyperParams', 'classification_colsample_bynode')
    op.drop_column('HyperParams', 'classification_early_stopping_rounds')
    op.drop_column('HyperParams', 'regression_colsample_bynode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HyperParams', sa.Column('regression_colsample_bynode', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('HyperParams', sa.Column('classification_early_stopping_rounds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('HyperParams', sa.Column('classification_colsample_bynode', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('HyperParams', sa.Column('regression_colsample_bylevel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('HyperParams', sa.Column('regression_early_stopping_rounds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('HyperParams', sa.Column('classification_colsample_bylevel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('HyperParams', 'classification_min_child_weight')
    op.drop_column('HyperParams', 'regression_min_child_weight')
    # ### end Alembic commands ###
