"""new_value_db_arch

Revision ID: 4842fa119fe5
Revises: baf7f52a5eed
Create Date: 2025-12-08 09:50:19.250564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4842fa119fe5'
down_revision: Union[str, Sequence[str], None] = 'baf7f52a5eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ValueBetSettings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sport', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('segmentKey', sa.String(), nullable=False),
    sa.Column('segmentJsCondition', sa.String(), nullable=False),
    sa.Column('segmentVariance', sa.Float(), nullable=False),
    sa.Column('segmentReliability', sa.Float(), nullable=False),
    sa.Column('segmentThreshold', sa.Float(), nullable=False),
    sa.Column('sampleSize', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segment_sport_unique', 'ValueBetSettings', ['segmentKey', 'sport'], unique=True)
    op.add_column('Sports', sa.Column('variance', sa.Float(), nullable=True))
    op.add_column('Sports', sa.Column('calibrationECE', sa.Float(), nullable=True))
    op.add_column('Sports', sa.Column('reliabilityWeight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'reliabilityWeight')
    op.drop_column('Sports', 'calibrationECE')
    op.drop_column('Sports', 'variance')
    op.drop_index('ix_segment_sport_unique', table_name='ValueBetSettings')
    op.drop_table('ValueBetSettings')
    # ### end Alembic commands ###
