"""adding value fields to sports

Revision ID: 4bace791e7ff
Revises: 7671480a12c9
Create Date: 2025-12-30 19:58:06.560327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bace791e7ff'
down_revision: Union[str, Sequence[str], None] = '7671480a12c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('value_threshold', sa.Float(), nullable=True))
    op.add_column('Sports', sa.Column('value_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'value_map')
    op.drop_column('Sports', 'value_threshold')
    # ### end Alembic commands ###
