"""tables check

Revision ID: 5e4fd1fb5413
Revises: 39d2278f2458
Create Date: 2025-11-03 10:30:09.769179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4fd1fb5413'
down_revision: Union[str, Sequence[str], None] = '39d2278f2458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('prevStatYear', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'prevStatYear')
    # ### end Alembic commands ###
