"""add_cascade_to_bookmaker_delete

Revision ID: 6b765d6cc1a7
Revises: 29ab340ce81c
Create Date: 2026-01-01 09:11:40.790477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b765d6cc1a7'
down_revision: Union[str, Sequence[str], None] = '29ab340ce81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Markets_bookmakerId_fkey'), 'Markets', type_='foreignkey')
    op.create_foreign_key(None, 'Markets', 'Bookmakers', ['bookmakerId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Outcomes_marketId_fkey'), 'Outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'Outcomes', 'Markets', ['marketId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Outcomes', type_='foreignkey')
    op.create_foreign_key(op.f('Outcomes_marketId_fkey'), 'Outcomes', 'Markets', ['marketId'], ['id'])
    op.drop_constraint(None, 'Markets', type_='foreignkey')
    op.create_foreign_key(op.f('Markets_bookmakerId_fkey'), 'Markets', 'Bookmakers', ['bookmakerId'], ['id'])
    # ### end Alembic commands ###
