"""adding value fields to sports

Revision ID: 7671480a12c9
Revises: be0de54ba139
Create Date: 2025-12-30 19:57:33.934647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7671480a12c9'
down_revision: Union[str, Sequence[str], None] = 'be0de54ba139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('value_threshold', sa.Float(), nullable=True))
    op.add_column('Sports', sa.Column('value_map', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'value_map')
    op.drop_column('Sports', 'value_threshold')
    # ### end Alembic commands ###
