"""new_hyperparam_columns

Revision ID: 8d0d0ac9dde8
Revises: c30cf8edb822
Create Date: 2025-11-09 09:52:39.331255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0d0ac9dde8'
down_revision: Union[str, Sequence[str], None] = 'c30cf8edb822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HyperParams', sa.Column('regression_early_stopping_rounds', sa.Integer(), nullable=True))
    op.add_column('HyperParams', sa.Column('classification_early_stopping_rounds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('HyperParams', 'classification_early_stopping_rounds')
    op.drop_column('HyperParams', 'regression_early_stopping_rounds')
    # ### end Alembic commands ###
