"""add_threshold_column_to_sports

Revision ID: ab8faae36795
Revises: fa03e8691654
Create Date: 2025-12-08 10:35:27.828583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8faae36795'
down_revision: Union[str, Sequence[str], None] = 'fa03e8691654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sports', 'threshold')
    # ### end Alembic commands ###
