"""new_value_db_arch

Revision ID: baf7f52a5eed
Revises: dbb4246e22ca
Create Date: 2025-12-08 09:48:46.504480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf7f52a5eed'
down_revision: Union[str, Sequence[str], None] = 'dbb4246e22ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sports', sa.Column('variance', sa.Float(), nullable=True))
    op.add_column('Sports', sa.Column('calibrationECE', sa.Float(), nullable=True))
    op.add_column('Sports', sa.Column('reliabilityWeight', sa.Float(), nullable=True))
    op.add_column('ValueBetSettings', sa.Column('segmentKey', sa.String(), nullable=False))
    op.add_column('ValueBetSettings', sa.Column('segmentJsCondition', sa.String(), nullable=False))
    op.add_column('ValueBetSettings', sa.Column('segmentVariance', sa.Float(), nullable=False))
    op.add_column('ValueBetSettings', sa.Column('segmentReliability', sa.Float(), nullable=False))
    op.add_column('ValueBetSettings', sa.Column('segmentThreshold', sa.Float(), nullable=False))
    op.add_column('ValueBetSettings', sa.Column('sampleSize', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_sport_unique'), table_name='ValueBetSettings')
    op.create_index('ix_segment_sport_unique', 'ValueBetSettings', ['segmentKey', 'sport'], unique=True)
    op.drop_column('ValueBetSettings', 'bestConfidenceInterval')
    op.drop_column('ValueBetSettings', 'bestCIScore')
    op.drop_column('ValueBetSettings', 'indexDiffSmall')
    op.drop_column('ValueBetSettings', 'confidenceRange')
    op.drop_column('ValueBetSettings', 'indexDiffRange')
    op.drop_column('ValueBetSettings', 'confidenceSmall')
    op.drop_column('ValueBetSettings', 'bestTotalGames')
    op.drop_column('ValueBetSettings', 'bestWinrate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ValueBetSettings', sa.Column('bestWinrate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('bestTotalGames', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('confidenceSmall', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('indexDiffRange', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('confidenceRange', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('indexDiffSmall', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('bestCIScore', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('bestConfidenceInterval', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.drop_index('ix_segment_sport_unique', table_name='ValueBetSettings')
    op.create_index(op.f('ix_sport_unique'), 'ValueBetSettings', ['bookmaker', 'sport'], unique=True)
    op.drop_column('ValueBetSettings', 'sampleSize')
    op.drop_column('ValueBetSettings', 'segmentThreshold')
    op.drop_column('ValueBetSettings', 'segmentReliability')
    op.drop_column('ValueBetSettings', 'segmentVariance')
    op.drop_column('ValueBetSettings', 'segmentJsCondition')
    op.drop_column('ValueBetSettings', 'segmentKey')
    op.drop_column('Sports', 'reliabilityWeight')
    op.drop_column('Sports', 'calibrationECE')
    op.drop_column('Sports', 'variance')
    # ### end Alembic commands ###
