"""add_value_score_to_games

Revision ID: be0de54ba139
Revises: ab8faae36795
Create Date: 2025-12-25 15:21:23.958903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0de54ba139'
down_revision: Union[str, Sequence[str], None] = 'ab8faae36795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Games', sa.Column('value_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Games', 'value_score')
    # ### end Alembic commands ###
