"""create tables_v3

Revision ID: d80cfda221dd
Revises: f244ff004232
Create Date: 2025-11-17 08:54:19.635616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80cfda221dd'
down_revision: Union[str, Sequence[str], None] = 'f244ff004232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oddsApiID', sa.String(), nullable=False),
    sa.Column('homeTeam', sa.Integer(), nullable=False),
    sa.Column('awayTeam', sa.Integer(), nullable=False),
    sa.Column('sport_title', sa.String(), nullable=False),
    sa.Column('sport_key', sa.String(), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('homeTeamIndex', sa.Float(), nullable=False),
    sa.Column('awayTeamIndex', sa.Float(), nullable=False),
    sa.Column('homeTeamScaledIndex', sa.Float(), nullable=False),
    sa.Column('awayTeamScaledIndex', sa.Float(), nullable=False),
    sa.Column('winPercent', sa.Float(), nullable=False),
    sa.Column('predictedWinner', sa.String(), nullable=False),
    sa.Column('predictionConfidence', sa.Float(), nullable=False),
    sa.Column('homeScore', sa.Integer(), nullable=True),
    sa.Column('awayScore', sa.Integer(), nullable=True),
    sa.Column('timeRemaining', sa.String(), nullable=True),
    sa.Column('sport', sa.Integer(), nullable=False),
    sa.Column('predictionCorrect', sa.Boolean(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('predictedHomeScore', sa.Integer(), nullable=False),
    sa.Column('predictedAwayScore', sa.Integer(), nullable=False),
    sa.Column('probablePitcher', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['awayTeam'], ['Teams.id'], ),
    sa.ForeignKeyConstraint(['homeTeam'], ['Teams.id'], ),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oddsApiID')
    )
    op.create_index('ix_sport_complete', 'Games', ['sport_key', 'complete'], unique=False)
    op.create_index('uq_game_unique', 'Games', ['homeTeam', 'awayTeam', 'commence_time', 'sport'], unique=True)
    op.create_table('Bookmakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['Games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookmaker_game', 'Bookmakers', ['gameId', 'key'], unique=True)
    op.create_table('Stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['Games.id'], ),
    sa.ForeignKeyConstraint(['sport'], ['Sports.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['Teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_team_unique', 'Stats', ['gameId', 'teamId'], unique=True)
    op.create_table('Markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmakerId', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bookmakerId'], ['Bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_bookmaker_key', 'Markets', ['bookmakerId', 'key'], unique=True)
    op.create_table('Outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('impliedProbability', sa.Float(), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['marketId'], ['Markets.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['Teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outcome_market_name', 'Outcomes', ['marketId', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outcome_market_name', table_name='Outcomes')
    op.drop_table('Outcomes')
    op.drop_index('ix_market_bookmaker_key', table_name='Markets')
    op.drop_table('Markets')
    op.drop_index('ix_game_team_unique', table_name='Stats')
    op.drop_table('Stats')
    op.drop_index('ix_bookmaker_game', table_name='Bookmakers')
    op.drop_table('Bookmakers')
    op.drop_index('uq_game_unique', table_name='Games')
    op.drop_index('ix_sport_complete', table_name='Games')
    op.drop_table('Games')
    # ### end Alembic commands ###
