"""tables check

Revision ID: f251a2255e22
Revises: 5d84bd669bb1
Create Date: 2025-11-03 10:19:11.093151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f251a2255e22'
down_revision: Union[str, Sequence[str], None] = '5d84bd669bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PastGames')
    op.drop_table('SequelizeMeta')
    op.drop_index(op.f('bookmakers_game_id_key'), table_name='Bookmakers')
    op.create_index('ix_bookmaker_game', 'Bookmakers', ['gameId', 'key'], unique=True)
    op.drop_constraint(op.f('Bookmakers_sport_fkey'), 'Bookmakers', type_='foreignkey')
    op.drop_constraint(op.f('Bookmakers_gameId_fkey'), 'Bookmakers', type_='foreignkey')
    op.create_foreign_key(None, 'Bookmakers', 'Games', ['gameId'], ['id'])
    op.drop_column('Bookmakers', 'updatedAt')
    op.drop_column('Bookmakers', 'sport')
    op.drop_column('Bookmakers', 'createdAt')
    op.alter_column('Games', 'commence_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('Games', 'probablePitcher',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('games_home_team_away_team_commence_time_sport'), table_name='Games')
    op.drop_index(op.f('games_sport_key_complete'), table_name='Games')
    op.create_index('ix_sport_complete', 'Games', ['sport_key', 'complete'], unique=False)
    op.create_index('uq_game_unique', 'Games', ['homeTeam', 'awayTeam', 'commence_time', 'sport'], unique=True)
    op.drop_constraint(op.f('Games_homeTeam_fkey'), 'Games', type_='foreignkey')
    op.drop_constraint(op.f('Games_sport_fkey'), 'Games', type_='foreignkey')
    op.drop_constraint(op.f('Games_awayTeam_fkey'), 'Games', type_='foreignkey')
    op.create_foreign_key(None, 'Games', 'Teams', ['homeTeam'], ['id'])
    op.create_foreign_key(None, 'Games', 'Sports', ['sport'], ['id'])
    op.create_foreign_key(None, 'Games', 'Teams', ['awayTeam'], ['id'])
    op.drop_column('Games', 'updatedAt')
    op.drop_column('Games', 'createdAt')
    op.alter_column('HyperParams', 'scoreMAE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('HyperParams', 'spreadMAE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('HyperParams', 'totalMAE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint(None, 'HyperParams', ['sport'])
    op.drop_constraint(op.f('HyperParams_sport_fkey'), 'HyperParams', type_='foreignkey')
    op.create_foreign_key(None, 'HyperParams', 'Sports', ['sport'], ['id'])
    op.drop_column('HyperParams', 'updatedAt')
    op.drop_column('HyperParams', 'kernalInitializer')
    op.drop_column('HyperParams', 'createdAt')
    op.drop_index(op.f('markets_bookmaker_id_key'), table_name='Markets')
    op.create_index('ix_market_bookmaker_key', 'Markets', ['bookmakerId', 'key'], unique=True)
    op.drop_constraint(op.f('Markets_bookmakerId_fkey'), 'Markets', type_='foreignkey')
    op.create_foreign_key(None, 'Markets', 'Bookmakers', ['bookmakerId'], ['id'])
    op.drop_column('Markets', 'updatedAt')
    op.drop_column('Markets', 'createdAt')
    op.alter_column('MlModelWeights', 'featureImportanceScores',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('MlModelWeights', 'hiddenToOutputWeights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('MlModelWeights', 'inputToHiddenWeights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ml_model_weights_sport'), table_name='MlModelWeights')
    op.create_index(op.f('ix_MlModelWeights_id'), 'MlModelWeights', ['id'], unique=False)
    op.create_unique_constraint(None, 'MlModelWeights', ['sport'])
    op.drop_constraint(op.f('MlModelWeights_sport_fkey'), 'MlModelWeights', type_='foreignkey')
    op.create_foreign_key(None, 'MlModelWeights', 'Sports', ['sport'], ['id'])
    op.drop_column('MlModelWeights', 'updatedAt')
    op.drop_column('MlModelWeights', 'createdAt')
    op.drop_index(op.f('outcomes_market_id_name'), table_name='Outcomes')
    op.create_index('ix_outcome_market_name', 'Outcomes', ['marketId', 'name'], unique=True)
    op.drop_constraint(op.f('Outcomes_teamId_fkey'), 'Outcomes', type_='foreignkey')
    op.drop_constraint(op.f('Outcomes_marketId_fkey'), 'Outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'Outcomes', 'Markets', ['marketId'], ['id'])
    op.create_foreign_key(None, 'Outcomes', 'Teams', ['teamId'], ['id'])
    op.drop_column('Outcomes', 'createdAt')
    op.drop_column('Outcomes', 'updatedAt')
    op.alter_column('Sports', 'sigmoidIQRSharpness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('Sports', 'averageIndex',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_Sports_id'), 'Sports', ['id'], unique=False)
    op.drop_column('Sports', 'createdAt')
    op.drop_column('Sports', 'updatedAt')
    op.alter_column('Stats', 'sport',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('Stats', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('Stats', 'createdAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('Stats', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index(op.f('stats_game_id_team_id'), table_name='Stats')
    op.create_index('ix_game_team_unique', 'Stats', ['gameId', 'teamId'], unique=True)
    op.drop_constraint(op.f('Stats_gameId_fkey'), 'Stats', type_='foreignkey')
    op.drop_constraint(op.f('Stats_teamId_fkey'), 'Stats', type_='foreignkey')
    op.create_foreign_key(None, 'Stats', 'Games', ['gameId'], ['id'])
    op.create_foreign_key(None, 'Stats', 'Sports', ['sport'], ['id'])
    op.create_foreign_key(None, 'Stats', 'Teams', ['teamId'], ['id'])
    op.alter_column('Teams', 'currentStats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('Teams', 'espnLeague',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Teams', 'statCategoryIndexes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('Teams', 'pitcherStats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('Teams', 'updatedAt')
    op.drop_column('Teams', 'createdAt')
    op.drop_index(op.f('value_bet_settings_sport_bookmaker'), table_name='ValueBetSettings')
    op.create_index('ix_sport_unique', 'ValueBetSettings', ['bookmaker'], unique=True)
    op.drop_constraint(op.f('ValueBetSettings_sport_fkey'), 'ValueBetSettings', type_='foreignkey')
    op.create_foreign_key(None, 'ValueBetSettings', 'Sports', ['sport'], ['id'])
    op.drop_column('ValueBetSettings', 'createdAt')
    op.drop_column('ValueBetSettings', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ValueBetSettings', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('ValueBetSettings', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ValueBetSettings', type_='foreignkey')
    op.create_foreign_key(op.f('ValueBetSettings_sport_fkey'), 'ValueBetSettings', 'Sports', ['sport'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_sport_unique', table_name='ValueBetSettings')
    op.create_index(op.f('value_bet_settings_sport_bookmaker'), 'ValueBetSettings', ['sport', 'bookmaker'], unique=True)
    op.add_column('Teams', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('Teams', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('Teams', 'pitcherStats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('Teams', 'statCategoryIndexes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('Teams', 'espnLeague',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Teams', 'currentStats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'Stats', type_='foreignkey')
    op.drop_constraint(None, 'Stats', type_='foreignkey')
    op.drop_constraint(None, 'Stats', type_='foreignkey')
    op.create_foreign_key(op.f('Stats_teamId_fkey'), 'Stats', 'Teams', ['teamId'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('Stats_gameId_fkey'), 'Stats', 'Games', ['gameId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_game_team_unique', table_name='Stats')
    op.create_index(op.f('stats_game_id_team_id'), 'Stats', ['gameId', 'teamId'], unique=True)
    op.alter_column('Stats', 'updatedAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('Stats', 'createdAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('Stats', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('Stats', 'sport',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('Sports', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('Sports', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_Sports_id'), table_name='Sports')
    op.alter_column('Sports', 'averageIndex',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('Sports', 'sigmoidIQRSharpness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('Outcomes', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('Outcomes', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Outcomes', type_='foreignkey')
    op.drop_constraint(None, 'Outcomes', type_='foreignkey')
    op.create_foreign_key(op.f('Outcomes_marketId_fkey'), 'Outcomes', 'Markets', ['marketId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('Outcomes_teamId_fkey'), 'Outcomes', 'Teams', ['teamId'], ['id'], onupdate='CASCADE')
    op.drop_index('ix_outcome_market_name', table_name='Outcomes')
    op.create_index(op.f('outcomes_market_id_name'), 'Outcomes', ['marketId', 'name'], unique=True)
    op.add_column('MlModelWeights', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('MlModelWeights', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'MlModelWeights', type_='foreignkey')
    op.create_foreign_key(op.f('MlModelWeights_sport_fkey'), 'MlModelWeights', 'Sports', ['sport'], ['id'], onupdate='CASCADE')
    op.drop_constraint(None, 'MlModelWeights', type_='unique')
    op.drop_index(op.f('ix_MlModelWeights_id'), table_name='MlModelWeights')
    op.create_index(op.f('ml_model_weights_sport'), 'MlModelWeights', ['sport'], unique=True)
    op.alter_column('MlModelWeights', 'inputToHiddenWeights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('MlModelWeights', 'hiddenToOutputWeights',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('MlModelWeights', 'featureImportanceScores',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('Markets', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('Markets', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Markets', type_='foreignkey')
    op.create_foreign_key(op.f('Markets_bookmakerId_fkey'), 'Markets', 'Bookmakers', ['bookmakerId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_market_bookmaker_key', table_name='Markets')
    op.create_index(op.f('markets_bookmaker_id_key'), 'Markets', ['bookmakerId', 'key'], unique=True)
    op.add_column('HyperParams', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('HyperParams', sa.Column('kernalInitializer', sa.VARCHAR(length=255), server_default=sa.text("'glorotUniform'::character varying"), autoincrement=False, nullable=False))
    op.add_column('HyperParams', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'HyperParams', type_='foreignkey')
    op.create_foreign_key(op.f('HyperParams_sport_fkey'), 'HyperParams', 'Sports', ['sport'], ['id'], onupdate='CASCADE')
    op.drop_constraint(None, 'HyperParams', type_='unique')
    op.alter_column('HyperParams', 'totalMAE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('HyperParams', 'spreadMAE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('HyperParams', 'scoreMAE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('Games', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('Games', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Games', type_='foreignkey')
    op.drop_constraint(None, 'Games', type_='foreignkey')
    op.drop_constraint(None, 'Games', type_='foreignkey')
    op.create_foreign_key(op.f('Games_awayTeam_fkey'), 'Games', 'Teams', ['awayTeam'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('Games_sport_fkey'), 'Games', 'Sports', ['sport'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('Games_homeTeam_fkey'), 'Games', 'Teams', ['homeTeam'], ['id'], onupdate='CASCADE')
    op.drop_index('uq_game_unique', table_name='Games')
    op.drop_index('ix_sport_complete', table_name='Games')
    op.create_index(op.f('games_sport_key_complete'), 'Games', ['sport_key', 'complete'], unique=False)
    op.create_index(op.f('games_home_team_away_team_commence_time_sport'), 'Games', ['homeTeam', 'awayTeam', 'commence_time', 'sport'], unique=True)
    op.alter_column('Games', 'probablePitcher',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('Games', 'commence_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('Bookmakers', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('Bookmakers', sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Bookmakers', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Bookmakers', type_='foreignkey')
    op.create_foreign_key(op.f('Bookmakers_gameId_fkey'), 'Bookmakers', 'Games', ['gameId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('Bookmakers_sport_fkey'), 'Bookmakers', 'Sports', ['sport'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index('ix_bookmaker_game', table_name='Bookmakers')
    op.create_index(op.f('bookmakers_game_id_key'), 'Bookmakers', ['gameId', 'key'], unique=True)
    op.create_table('SequelizeMeta',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('SequelizeMeta_pkey'))
    )
    op.create_table('PastGames',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('homeTeam', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awayTeam', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commence_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('homeTeamIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('awayTeamIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('homeTeamScaledIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('awayTeamScaledIndex', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('winPercent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('predictedWinner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('predictionConfidence', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('homeScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('awayScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeRemaining', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bookmakers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('homeStats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awayStats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PastGames_pkey'))
    )
    # ### end Alembic commands ###
