"""remove bookmaker column

Revision ID: fa03e8691654
Revises: 4842fa119fe5
Create Date: 2025-12-08 10:14:05.735641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa03e8691654'
down_revision: Union[str, Sequence[str], None] = '4842fa119fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ValueBetSettings', 'bookmaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ValueBetSettings', sa.Column('bookmaker', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
