const baseballStatMap = [
  'seasonWinLoss',
  'homeWinLoss',
  'awayWinLoss',
  'pointDiff',
  'BSBbattingStrikeouts',
  'BSBrunsBattedIn',
  'BSBsacrificeHits',
  'BSBHitsTotal',
  'BSBwalks',
  'BSBruns',
  'BSBhomeRuns',
  'BSBdoubles',
  'BSBtotalBases',
  'BSBextraBaseHits',
  'BSBbattingAverage',
  'BSBsluggingPercentage',
  'BSBonBasePercentage',
  'BSBonBasePlusSlugging',
  'BSBgroundToFlyRatio',
  'BSBatBatsPerHomeRun',
  'BSBstolenBasePercentage',
  'BSBbatterWalkToStrikeoutRatio',
  'BSBsaves',
  'BSBpitcherStrikeouts',
  'BSBhitsGivenUp',
  'BSBearnedRuns',
  'BSBbattersWalked',
  'BSBrunsAllowed',
  'BSBhomeRunsAllowed',
  'BSBwins',
  'BSBshutouts',
  'BSBearnedRunAverage',
  'BSBwalksHitsPerInningPitched',
  'BSBwinPct',
  'BSBpitcherCaughtStealingPct',
  'BSBpitchesPerInning',
  'BSBrunSupportAverage',
  'BSBopponentBattingAverage',
  'BSBopponentSlugAverage',
  'BSBopponentOnBasePct',
  'BSBopponentOnBasePlusSlugging',
  'BSBsavePct',
  'BSBstrikeoutsPerNine',
  'BSBpitcherStrikeoutToWalkRatio',
  'BSBdoublePlays',
  'BSBerrors',
  'BSBpassedBalls',
  'BSBassists',
  'BSBputouts',
  'BSBcatcherCaughtStealing',
  'BSBcatcherCaughtStealingPct',
  'BSBcatcherStolenBasesAllowed',
  'BSBfieldingPercentage',
  'BSBrangeFactor'
];

const battingStats = [
  'BSBbattingStrikeouts',
  'BSBrunsBattedIn',
  'BSBsacrificeHits',
  'BSBHitsTotal',
  'BSBwalks',
  'BSBruns',
  'BSBhomeRuns',
  'BSBdoubles',
  'BSBtotalBases',
  'BSBextraBaseHits',
  'BSBbattingAverage',
  'BSBsluggingPercentage',
  'BSBonBasePercentage',
  'BSBonBasePlusSlugging',
  'BSBgroundToFlyRatio',
  'BSBatBatsPerHomeRun',
  'BSBstolenBasePercentage',
  'BSBbatterWalkToStrikeoutRatio'
];

const pitchingStats = [
  'BSBsaves',
  'BSBpitcherStrikeouts',
  'BSBhitsGivenUp',
  'BSBearnedRuns',
  'BSBbattersWalked',
  'BSBrunsAllowed',
  'BSBhomeRunsAllowed',
  'BSBwins',
  'BSBshutouts',
  'BSBearnedRunAverage',
  'BSBwalksHitsPerInningPitched',
  'BSBwinPct',
  'BSBpitcherCaughtStealingPct',
  'BSBpitchesPerInning',
  'BSBrunSupportAverage',
  'BSBopponentBattingAverage',
  'BSBopponentSlugAverage',
  'BSBopponentOnBasePct',
  'BSBopponentOnBasePlusSlugging',
  'BSBsavePct',
  'BSBstrikeoutsPerNine',
  'BSBpitcherStrikeoutToWalkRatio'
];

const fieldingStats = [
  'BSBdoublePlays',
  'BSBerrors',
  'BSBpassedBalls',
  'BSBassists',
  'BSBputouts',
  'BSBcatcherCaughtStealing',
  'BSBcatcherCaughtStealingPct',
  'BSBcatcherStolenBasesAllowed',
  'BSBfieldingPercentage',
  'BSBrangeFactor'
];

const generalStats = [
  'seasonWinLoss',
  'homeWinLoss',
  'awayWinLoss',
  'pointDiff'
];

const basketballStatMap = [
  'seasonWinLoss',
  'homeWinLoss',
  'awayWinLoss',
  'pointDiff',
  'BSKBtotalPoints',
  'BSKBpointsPerGame',
  'BSKBassists',
  'BSKBassistsPerGame',
  'BSKBassistRatio',
  'BSKBeffectiveFgPercent',
  'BSKBfieldGoalPercent',
  'BSKBfieldGoalsAttempted',
  'BSKBfieldGoalsMade',
  'BSKBfieldGoalsPerGame',
  'BSKBfreeThrowPercent',
  'BSKBfreeThrowsAttempted',
  'BSKBfreeThrowsMade',
  'BSKBfreeThrowsMadePerGame',
  'BSKBoffensiveRebounds',
  'BSKBoffensiveReboundsPerGame',
  'BSKBoffensiveReboundRate',
  'BSKBoffensiveTurnovers',
  'BSKBturnoversPerGame',
  'BSKBturnoverRatio',
  'BSKBthreePointPct',
  'BSKBthreePointsAttempted',
  'BSKBthreePointsMade',
  'BSKBtrueShootingPct',
  'BSKBpace',
  'BSKBpointsInPaint',
  'BSKBshootingEfficiency',
  'BSKBscoringEfficiency',
  'BSKBblocks',
  'BSKBblocksPerGame',
  'BSKBdefensiveRebounds',
  'BSKBdefensiveReboundsPerGame',
  'BSKBsteals',
  'BSKBstealsPerGame',
  'BSKBreboundRate',
  'BSKBreboundsPerGame',
  'BSKBfoulsPerGame',
  'BSKBteamAssistToTurnoverRatio',

];

const basketballOffenseStats = [
  'BSKBtotalPoints',
  'BSKBpointsPerGame',
  'BSKBassists',
  'BSKBassistsPerGame',
  'BSKBassistRatio',
  'BSKBeffectiveFgPercent',
  'BSKBfieldGoalPercent',
  'BSKBfieldGoalsAttempted',
  'BSKBfieldGoalsMade',
  'BSKBfieldGoalsPerGame',
  'BSKBfreeThrowPercent',
  'BSKBfreeThrowsAttempted',
  'BSKBfreeThrowsMade',
  'BSKBfreeThrowsMadePerGame',
  'BSKBoffensiveRebounds',
  'BSKBoffensiveReboundsPerGame',
  'BSKBoffensiveReboundRate',
  'BSKBoffensiveTurnovers',
  'BSKBturnoversPerGame',
  'BSKBturnoverRatio',
  'BSKBthreePointPct',
  'BSKBthreePointsAttempted',
  'BSKBthreePointsMade',
  'BSKBtrueShootingPct',
  'BSKBpace',
  'BSKBpointsInPaint',
  'BSKBshootingEfficiency',
  'BSKBscoringEfficiency',
  'BSKBteamAssistToTurnoverRatio'
]

const basketballDefenseStats = [
  'BSKBblocks',
  'BSKBblocksPerGame',
  'BSKBdefensiveRebounds',
  'BSKBdefensiveReboundsPerGame',
  'BSKBsteals',
  'BSKBstealsPerGame',
  'BSKBreboundRate',
  'BSKBreboundsPerGame',
  'BSKBfoulsPerGame'
]

const hockeyStatMap = [
  'seasonWinLoss',
  'homeWinLoss',
  'awayWinLoss',
  'pointDiff',
  'HKYgoals',
  'HKYgoalsPerGame',
  'HKYassists',
  'HKYassistsPerGame',
  'HKYshotsIn1st',
  'HKYshotsIn1stPerGame',
  'HKYshotsIn2nd',
  'HKYshotsIn2ndPerGame',
  'HKYshotsIn3rd',
  'HKYshotsIn3rdPerGame',
  'HKYtotalShots',
  'HKYtotalShotsPerGame',
  'HKYshotsMissed',
  'HKYshotsMissedPerGame',
  'HKYppgGoals',
  'HKYppgGoalsPerGame',
  'HKYppassists',
  'HKYppassistsPerGame',
  'HKYpowerplayPct',
  'HKYshortHandedGoals',
  'HKYshortHandedGoalsPerGame',
  'HKYshootingPct',
  'HKYfaceoffs',
  'HKYfaceoffsPerGame',
  'HKYfaceoffsWon',
  'HKYfaceoffsWonPerGame',
  'HKYfaceoffsLost',
  'HKYfaceoffsLostPerGame',
  'HKYfaceoffPct',
  'HKYfaceoffPctPerGame',
  'HKYgiveaways',
  'HKYgoalsAgainst',
  'HKYgoalsAgainstPerGame',
  'HKYshotsAgainst',
  'HKYshotsAgainstPerGame',
  'HKYpenaltyKillPct',
  'HKYpenaltyKillPctPerGame',
  'HKYppGoalsAgainst',
  'HKYppGoalsAgainstPerGame',
  'HKYshutouts',
  'HKYsaves',
  'HKYsavesPerGame',
  'HKYsavePct',
  'HKYblockedShots',
  'HKYblockedShotsPerGame',
  'HKYhits',
  'HKYhitsPerGame',
  'HKYtakeaways',
  'HKYtakeawaysPerGame',
  'HKYshotDifferential',
  'HKYshotDifferentialPerGame',
  'HKYgoalDifferentialPerGame',
  'HKYpimDifferential',
  'HKYpimDifferentialPerGame',
  'HKYtotalPenalties',
  'HKYpenaltiesPerGame',
  'HKYpenaltyMinutes',
  'HKYpenaltyMinutesPerGame',
];

const hockeyOffenseStats = [
  'HKYgoals',
  'HKYgoalsPerGame',
  'HKYassists',
  'HKYassistsPerGame',
  'HKYshotsIn1st',
  'HKYshotsIn1stPerGame',
  'HKYshotsIn2nd',
  'HKYshotsIn2ndPerGame',
  'HKYshotsIn3rd',
  'HKYshotsIn3rdPerGame',
  'HKYtotalShots',
  'HKYtotalShotsPerGame',
  'HKYshotsMissed',
  'HKYshotsMissedPerGame',
  'HKYppgGoals',
  'HKYppgGoalsPerGame',
  'HKYppassists',
  'HKYppassistsPerGame',
  'HKYpowerplayPct',
  'HKYshortHandedGoals',
  'HKYshortHandedGoalsPerGame',
  'HKYshootingPct',
  'HKYfaceoffs',
  'HKYfaceoffsPerGame',
  'HKYfaceoffsWon',
  'HKYfaceoffsWonPerGame',
  'HKYfaceoffsLost',
  'HKYfaceoffsLostPerGame',
  'HKYfaceoffPct',
  'HKYfaceoffPctPerGame',
  'HKYgiveaways',
  'HKYshotDifferential',
  'HKYshotDifferentialPerGame',
  'HKYgoalDifferentialPerGame'
]

const hockeyDefenseStats = [
  'HKYgoalsAgainst',
  'HKYgoalsAgainstPerGame',
  'HKYshotsAgainst',
  'HKYshotsAgainstPerGame',
  'HKYpenaltyKillPct',
  'HKYpenaltyKillPctPerGame',
  'HKYppGoalsAgainst',
  'HKYppGoalsAgainstPerGame',
  'HKYshutouts',
  'HKYsaves',
  'HKYsavesPerGame',
  'HKYsavePct',
  'HKYblockedShots',
  'HKYblockedShotsPerGame',
  'HKYhits',
  'HKYhitsPerGame',
  'HKYtakeaways',
  'HKYtakeawaysPerGame'
]

const hockeyPenaltyStats = [
  'HKYpimDifferential',
  'HKYpimDifferentialPerGame',
  'HKYtotalPenalties',
  'HKYpenaltiesPerGame',
  'HKYpenaltyMinutes',
  'HKYpenaltyMinutesPerGame'
]

const footballStatMap = [
  'seasonWinLoss',
  'homeWinLoss',
  'awayWinLoss',
  'pointDiff',
  'USFBpointsPerGame',
  'USFBtotalPoints',
  'USFBtotalTouchdowns',
  'USFBtouchdownsPerGame',
  'USFBcompletionPercent',
  'USFBcompletions',
  'USFBcompletionsPerGame',
  'USFBnetPassingYards',
  'USFBnetPassingYardsPerGame',
  'USFBpassingFirstDowns',
  'USFBpassingYards',
  'USFBpassingYardsPerGame',
  'USFBpassingAttempts',
  'USFBpassingAttemptsPerGame',
  'USFByardsPerPassAttempt',
  'USFBrushingAttempts',
  'USFBrushingFirstDowns',
  'USFBrushingTouchdowns',
  'USFBrushingYards',
  'USFBrushingYardsPerGame',
  'USFByardsPerRushAttempt',
  'USFBreceivingFirstDowns',
  'USFBreceivingTouchdowns',
  'USFBreceivingYards',
  'USFBreceivingYardsPerGame',
  'USFBreceivingYardsPerReception',
  'USFBreceivingYardsAfterCatch',
  'USFBreceivingYardsAfterCatchPerGame',
  'USFBtacklesforLoss',
  'USFBtacklesforLossPerGame',
  'USFBinterceptions',
  'USFByardsPerInterception',
  'USFBsacksTotal',
  'USFBsacksPerGame',
  'USFBsackYards',
  'USFBsackYardsPerGame',
  'USFBstuffs',
  'USFBstuffsPerGame',
  'USFBstuffYards',
  'USFBpassesDefended',
  'USFBpassesDefendedPerGame',
  'USFBsafties',
  'USFBaverageKickoffYards',
  'USFBaverageKickoffYardsPerGame',
  'USFBextraPointAttempts',
  'USFBextraPointAttemptsPerGame',
  'USFBextraPointsMade',
  'USFBextraPointsMadePerGame',
  'USFBextraPointPercent',
  'USFBextraPointPercentPerGame',
  'USFBfieldGoalAttempts',
  'USFBfieldGoalAttemptsPerGame',
  'USFBfieldGoalsMade',
  'USFBfieldGoalsMadePerGame',
  'USFBfieldGoalPct',
  'USFBfieldGoalPercentPerGame',
  'USFBtouchbacks',
  'USFBtouchbacksPerGame',
  'USFBtouchBackPercentage',
  'USFBkickReturns',
  'USFBkickReturnsPerGame',
  'USFBkickReturnYards',
  'USFBkickReturnYardsPerGame',
  'USFBpuntReturns',
  'USFBpuntReturnsPerGame',
  'USFBpuntReturnFairCatchPct',
  'USFBpuntReturnYards',
  'USFBpuntReturnYardsPerGame',
  'USFByardsPerReturn',
  'USFBthirdDownEfficiency',
  'USFBtotalPenyards',
  'USFBaveragePenYardsPerGame',
  'USFBgiveaways',
  'USFBtakeaways',
  'USFBturnoverDiff',
  'USFBtotalFirstDowns',
];

const footballRushingStats = [
  'USFBrushingAttempts',
  'USFBrushingFirstDowns',
  'USFBrushingTouchdowns',
  'USFBrushingYards',
  'USFBrushingYardsPerGame',
  'USFByardsPerRushAttempt',
]

const footballPassingStats = [
  'USFBcompletionPercent',
  'USFBcompletions',
  'USFBcompletionsPerGame',
  'USFBnetPassingYards',
  'USFBnetPassingYardsPerGame',
  'USFBpassingFirstDowns',
  'USFBpassingYards',
  'USFBpassingYardsPerGame',
  'USFBpassingAttempts',
  'USFBpassingAttemptsPerGame',
  'USFByardsPerPassAttempt',
]

const footballRecievingStats = [
  'USFBreceivingFirstDowns',
  'USFBreceivingTouchdowns',
  'USFBreceivingYards',
  'USFBreceivingYardsPerGame',
  'USFBreceivingYardsPerReception',
  'USFBreceivingYardsAfterCatch',
  'USFBreceivingYardsAfterCatchPerGame',
]

const footballDefenseStats = [
  'USFBtacklesforLoss',
  'USFBtacklesforLossPerGame',
  'USFBinterceptions',
  'USFByardsPerInterception',
  'USFBsacksTotal',
  'USFBsacksPerGame',
  'USFBsackYards',
  'USFBsackYardsPerGame',
  'USFBstuffs',
  'USFBstuffsPerGame',
  'USFBstuffYards',
  'USFBpassesDefended',
  'USFBpassesDefendedPerGame',
  'USFBsafties',
]

const footballKickingStats = [
  'USFBextraPointAttempts',
  'USFBextraPointAttemptsPerGame',
  'USFBextraPointsMade',
  'USFBextraPointsMadePerGame',
  'USFBextraPointPercent',
  'USFBextraPointPercentPerGame',
  'USFBfieldGoalAttempts',
  'USFBfieldGoalAttemptsPerGame',
  'USFBfieldGoalsMade',
  'USFBfieldGoalsMadePerGame',
  'USFBfieldGoalPct',
  'USFBfieldGoalPercentPerGame',
  'USFBaverageKickoffYards',
  'USFBaverageKickoffYardsPerGame',
  'USFBtouchbacks',
  'USFBtouchbacksPerGame',
  'USFBtouchBackPercentage',
]

const footballReturningStats = [
  'USFBkickReturns',
  'USFBkickReturnsPerGame',
  'USFBkickReturnYards',
  'USFBkickReturnYardsPerGame',
  'USFBpuntReturns',
  'USFBpuntReturnsPerGame',
  'USFBpuntReturnFairCatchPct',
  'USFBpuntReturnYards',
  'USFBpuntReturnYardsPerGame',
  'USFByardsPerReturn',
]

const footballOtherStats = [
  'USFBtotalPenyards',
  'USFBaveragePenYardsPerGame',
  'USFBthirdDownEfficiency',
  'USFBtotalFirstDowns',
  'USFBgiveaways',
  'USFBtakeaways',
  'USFBturnoverDiff',
  'USFBpointsPerGame',
  'USFBtotalPoints',
  'USFBtotalTouchdowns',
  'USFBtouchdownsPerGame',
]
const statConfigMap = {
    baseball: {
        default: baseballStatMap,
        categories: {
            general: generalStats,
            batting: battingStats,
            pitching: pitchingStats,
            fielding: fieldingStats
        }
    },
    football: {
        default: footballStatMap,
        categories: {
            general: generalStats,
            passing: footballPassingStats,
            recieving: footballRecievingStats,
            rushing: footballRushingStats,
            defense: footballDefenseStats,
            kicking: footballKickingStats,
            returning: footballReturningStats,
            other: footballOtherStats
        }
    },
    basketball: {
        default: basketballStatMap,
        categories: {
            general: generalStats,
            offense: basketballOffenseStats,
            defense: basketballDefenseStats
        }
    },
    hockey: {
        default: hockeyStatMap,
        categories: {
            general: generalStats,
            offense: hockeyOffenseStats,
            defense: hockeyDefenseStats,
            penalty: hockeyPenaltyStats
        }
    }
};
module.exports = { baseballStatMap, basketballStatMap, hockeyStatMap, footballStatMap, battingStats, pitchingStats, fieldingStats, generalStats, footballDefenseStats, footballKickingStats, footballOtherStats, footballPassingStats, footballRecievingStats, footballReturningStats, footballRushingStats, hockeyDefenseStats, hockeyOffenseStats, hockeyPenaltyStats, basketballDefenseStats, basketballOffenseStats, statConfigMap };