americanfootball_ncaaf_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "gamesPlayed",
  "netTotalYards",
  "netYardsPerGame",
  "totalOffensivePlays",
  "totalYards",
  "totalYardsFromScrimmage",
  "yardsFromScrimmagePerGame",
  "yardsPerGame",
  "longRushing",
  "rushingAttempts",
  "firstDowns",
  "firstDownsPerGame",
  "passingAttempts",
  "possessionTimeSeconds",
  "thirdDownAttempts",
  "rushingYards",
  "rushingYardsPerGame",
  "yardsPerRushAttempt",
  "netPassingYards",
  "netPassingYardsPerGame",
  "netYardsPerPassAttempt",
  "ESPNWRRating",
  "receptions",
  "completionPct",
  "completions",
  "receivingYards",
  "receivingYardsAtCatch",
  "receivingYardsPerGame",
  "yardsPerReception",
  "passingYards",
  "passingYardsAtCatch",
  "passingYardsPerGame",
  "yardsPerCompletion",
  "yardsPerPassAttempt",
  "ESPNRBRating",
  "longReception",
  "ESPNQBRating",
  "longPassing",
  "firstDownsPassing",
  "firstDownsRushing",
  "kickoffs",
  "totalPenalties",
  "totalPenaltyYards",
  "thirdDownConvPct",
  "thirdDownConvs",
  "yardsAllowed",
  "punts",
  "grossAvgPuntYards",
  "puntYards",
  "longPunt",
  "totalPoints",
  "totalPointsPerGame",
  "sacks",
  "totalKickingPoints",
  "totalTouchdowns",
  "totalDrives",
  "yardsPerReturn",
  "extraPointAttempts",
  "kickExtraPoints",
  "kickExtraPointsMade",
  "extraPointPct",
  "extraPointsMade",
  "totalTackles",
  "soloTackles",
  "assistTackles",
  "tacklesForLoss",
  "kickReturns",
  "passesDefended",
  "kickReturnYards",
  "longKickReturn",
  "fourthDownAttempts",
  "kickoffReturns",
  "interceptions",
  "avgKickoffReturnYards",
  "touchbacks",
  "touchbackPct",
  "avgSackYards",
  "firstDownsPenalty",
  "passingTouchdowns",
  "sackYardsLost",
  "receivingTouchdowns",
  "passingTouchdownPct",
  "sackYards",
  "rushingTouchdowns",
  "fieldGoalAttempts",
  "puntReturns",
  "puntsInside20",
  "puntsInside20Pct",
  "hurries",
  "fumbles",
  "fieldGoalPct",
  "fieldGoalsMade",
  "fieldGoals",
  "fourthDownConvs",
  "fourthDownConvPct",
  "turnOverDifferential",
]

americanfootball_ncaaf_general_stats = ['gamesPlayed', 'fumbles', 'totalPoints', 'totalPointsPerGame', 'totalTouchdowns', 'kickExtraPoints', 'kickExtraPointsMade', 'fieldGoals']
americanfootball_ncaaf_passing_stats = ['netTotalYards', 'netYardsPerGame', 'totalOffensivePlays', 'totalYards', 'totalYardsFromScrimmage', 'yardsFromScrimmagePerGame', 'yardsPerGame', 'passingAttempts', 'netPassingYards', 'netPassingYardsPerGame', 'netYardsPerPassAttempt', 'completionPct', 'completions', 'passingYards', 'passingYardsAtCatch', 'passingYardsPerGame', 'yardsPerCompletion', 'yardsPerPassAttempt', 'ESPNQBRating', 'longPassing', 'qb_sacks', 'interceptions', 'passingTouchdowns', 'sackYardsLost', 'passingTouchdownPct']
americanfootball_ncaaf_receiving_stats = ['ESPNWRRating', 'receptions', 'receivingYards', 'receivingYardsAtCatch', 'receivingYardsPerGame', 'yardsPerReception', 'longReception', 'receivingTouchdowns']
americanfootball_ncaaf_rushing_stats = ['longRushing', 'rushingAttempts', 'rushingYards', 'rushingYardsPerGame', 'yardsPerRushAttempt', 'ESPNRBRating', 'rushingTouchdowns']
americanfootball_ncaaf_defensive_stats = ['yardsAllowed', 'sacks', 'totalTackles', 'soloTackles', 'assistTackles', 'tacklesForLoss', 'passesDefended', 'avgSackYards', 'sackYards', 'hurries', 'defensive_interceptions']
americanfootball_ncaaf_special_teams_stats = ['kickoffs', 'totalKickingPoints', 'extraPointAttempts', 'extraPointPct', 'extraPointsMade', 'kickoffReturns', 'touchbacks', 'touchbackPct', 'fieldGoalAttempts', 'fieldGoalPct', 'fieldGoalsMade', 'punts', 'grossAvgPuntYards', 'puntYards', 'longPunt', 'touchbacks_punting', 'touchbackPct_punting', 'puntsInside20', 'puntsInside20Pct', 'yardsPerReturn', 'kickReturns', 'kickReturnYards', 'longKickReturn', 'avgKickoffReturnYards', 'puntReturns']
americanfootball_ncaaf_miscellaneous_stats = ['firstDowns', 'firstDownsPerGame', 'possessionTimeSeconds', 'thirdDownAttempts', 'firstDownsPassing', 'firstDownsRushing', 'totalPenalties', 'totalPenaltyYards', 'thirdDownConvPct', 'thirdDownConvs', 'totalDrives', 'fourthDownAttempts', 'firstDownsPenalty', 'fourthDownConvs', 'fourthDownConvPct', 'turnOverDifferential']

americanfootball_nfl_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "gamesPlayed",
  "completionPct",
  "completions",
  "ESPNQBRating",
  "longPassing",
  "netPassingYards",
  "netPassingYardsPerGame",
  "netTotalYards",
  "netYardsPerGame",
  "passingAttempts",
  "passingYards",
  "passingYardsAtCatch",
  "passingYardsPerGame",
  "netPassingAttempts",
  "totalOffensivePlays",
  "totalYards",
  "totalYardsFromScrimmage",
  "yardsFromScrimmagePerGame",
  "yardsPerCompletion",
  "yardsPerGame",
  "yardsPerPassAttempt",
  "netYardsPerPassAttempt",
  "ESPNRBRating",
  "longRushing",
  "rushingAttempts",
  "rushingYards",
  "rushingYardsPerGame",
  "yardsPerRushAttempt",
  "ESPNWRRating",
  "longReception",
  "receivingTargets",
  "receivingYards",
  "receivingYardsAfterCatch",
  "receivingYardsPerGame",
  "receptions",
  "yardsPerReception",
  "assistTackles",
  "soloTackles",
  "totalTackles",
  "yardsAllowed",
  "kickoffs",
  "firstDowns",
  "firstDownsPerGame",
  "possessionTimeSeconds",
  "thirdDownAttempts",
  "totalDrives",
  "receivingYardsAtCatch",
  "firstDownsPassing",
  "totalPenalties",
  "totalPenaltyYards",
  "rushingFirstDowns",
  "firstDownsRushing",
  "thirdDownConvPct",
  "thirdDownConvs",
  "totalPoints",
  "totalPointsPerGame",
  "pointsAllowed",
  "sacks",
  "tacklesForLoss",
  "punts",
  "grossAvgPuntYards",
  "longPunt",
  "puntYards",
  "totalKickingPoints",
  "stuffs",
  "passesDefended",
  "yardsPerReturn",
  "puntReturns",
  "totalTouchdowns",
  "puntReturnYards",
  "touchbackPct",
  "touchbacks",
  "extraPointAttempts",
  "avgPuntReturnYards",
  "extraPointPct",
  "extraPointsMade",
  "kickExtraPoints",
  "kickExtraPointsMade",
  "fieldGoalAttempts",
  "fieldGoalAttemptYards",
  "twoPointRecConvs",
  "sackYardsLost",
  "avgSackYards",
  "sackYards",
  "passingFirstDowns",
  "fieldGoalsMadeYards",
  "longFieldGoalMade",
  "fieldGoalPct",
  "fieldGoalsMade",
  "fieldGoals",
  "firstDownsPenalty",
  "avgKickoffYards",
  "kickoffYards",
  "passingTouchdownPct",
  "passingTouchdowns",
  "receivingTouchdowns",
  "interceptions",
  "kickoffReturns",
  "kickReturns",
  "puntsInside20",
  "puntsInside20Pct",
  "avgKickoffReturnYards",
  "kickoffReturnYards",
  "kickReturnYards",
  "longKickReturn",
  "yardsPerPuntReturn",
  "longPuntReturn",
  "rushingTouchdowns",
  "turnOverDifferential",
]

americanfootball_nfl_general_stats = ['gamesPlayed', 'totalPoints', 'totalPointsPerGame', 'totalTouchdowns', 'kickExtraPoints', 'kickExtraPointsMade', 'fieldGoals']
americanfootball_nfl_passing_stats = ['completionPct', 'completions', 'ESPNQBRating', 'longPassing', 'netPassingYards', 'netPassingYardsPerGame', 'netTotalYards', 'netYardsPerGame', 'passingAttempts', 'passingYards', 'passingYardsAtCatch', 'passingYardsPerGame', 'netPassingAttempts', 'totalOffensivePlays', 'totalYards', 'totalYardsFromScrimmage', 'yardsFromScrimmagePerGame', 'yardsPerCompletion', 'yardsPerGame', 'yardsPerPassAttempt', 'netYardsPerPassAttempt', 'sackYardsLost', 'passingFirstDowns', 'passingTouchdownPct', 'passingTouchdowns', 'interceptions']
americanfootball_nfl_receiving_stats = ['ESPNWRRating', 'longReception', 'receivingTargets', 'receivingYards', 'receivingYardsAfterCatch', 'receivingYardsPerGame', 'receptions', 'yardsPerReception', 'receivingYardsAtCatch', 'twoPointRecConvs', 'receivingTouchdowns']
americanfootball_nfl_rushing_stats = ['ESPNRBRating', 'longRushing', 'rushingAttempts', 'rushingYards', 'rushingYardsPerGame', 'yardsPerRushAttempt', 'rushingFirstDowns', 'rushingTouchdowns']
americanfootball_nfl_defensive_stats = ['assistTackles', 'soloTackles', 'totalTackles', 'yardsAllowed', 'pointsAllowed', 'sacks', 'tacklesForLoss', 'stuffs', 'passesDefended', 'avgSackYards', 'sackYards', 'defensive_interceptions']
americanfootball_nfl_special_teams_stats = ['kickoffs', 'totalKickingPoints', 'touchbackPct', 'touchbacks', 'extraPointAttempts', 'extraPointPct', 'extraPointsMade', 'fieldGoalAttempts', 'fieldGoalAttemptYards', 'fieldGoalsMadeYards', 'longFieldGoalMade', 'fieldGoalPct', 'fieldGoalsMade', 'avgKickoffYards', 'kickoffYards', 'kickoffReturns', 'avgKickoffReturnYards', 'kickoffReturnYards', 'punts', 'grossAvgPuntYards', 'longPunt', 'puntYards', 'puntReturns', 'puntReturnYards', 'touchbacks_punting', 'touchbackPct_punting', 'avgPuntReturnYards', 'puntsInside20', 'puntsInside20Pct', 'yardsPerReturn', 'kickReturns', 'kickReturnYards', 'longKickReturn', 'yardsPerPuntReturn', 'longPuntReturn']
americanfootball_nfl_miscellaneous_stats = ['firstDowns', 'firstDownsPerGame', 'possessionTimeSeconds', 'thirdDownAttempts', 'totalDrives', 'firstDownsPassing', 'totalPenalties', 'totalPenaltyYards', 'firstDownsRushing', 'thirdDownConvPct', 'thirdDownConvs', 'firstDownsPenalty', 'turnOverDifferential']

basketball_nba_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "defensiveRebounds",
  "avgDefensiveRebounds",
  "fouls",
  "rebounds",
  "NBARating",
  "avgRebounds",
  "avgFouls",
  "assistTurnoverRatio",
  "totalRebounds",
  "gamesPlayed",
  "assists",
  "fieldGoals",
  "fieldGoalsAttempted",
  "fieldGoalsMade",
  "fieldGoalPct",
  "points",
  "turnovers",
  "threePointPct",
  "threePointFieldGoalsAttempted",
  "threePointFieldGoalsMade",
  "pointsInPaint",
  "avgFieldGoalsMade",
  "avgFieldGoalsAttempted",
  "avgThreePointFieldGoalsMade",
  "avgThreePointFieldGoalsAttempted",
  "avgPoints",
  "avgAssists",
  "avgTurnovers",
  "estimatedPossessions",
  "avgEstimatedPossessions",
  "pointsPerEstimatedPossessions",
  "threePointFieldGoalPct",
  "twoPointFieldGoalsMade",
  "twoPointFieldGoalsAttempted",
  "avgTwoPointFieldGoalsMade",
  "avgTwoPointFieldGoalsAttempted",
  "twoPointFieldGoalPct",
  "shootingEfficiency",
  "scoringEfficiency",
  "freeThrowPct",
  "freeThrowsAttempted",
  "freeThrowsMade",
  "avgFreeThrowsMade",
  "avgFreeThrowsAttempted",
  "offensiveRebounds",
  "avgOffensiveRebounds",
  "offensiveReboundPct",
  "totalTurnovers",
  "avgTotalTurnovers",
  "turnoverPoints",
  "steals",
  "avgSteals",
  "stealFoulRatio",
  "stealTurnoverRatio",
  "fastBreakPoints",
  "blocks",
  "avgBlocks",
  "blockFoulRatio",
]

basketball_nba_general_stats = ['fouls', 'rebounds', 'NBARating', 'avgRebounds', 'avgFouls', 'assistTurnoverRatio', 'totalRebounds', 'gamesPlayed', 'stealFoulRatio', 'stealTurnoverRatio', 'blockFoulRatio']
basketball_nba_offensive_stats = ['assists', 'fieldGoals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalPct', 'points', 'turnovers', 'threePointPct', 'threePointFieldGoalsAttempted', 'threePointFieldGoalsMade', 'pointsInPaint', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgThreePointFieldGoalsMade', 'avgThreePointFieldGoalsAttempted', 'avgPoints', 'avgAssists', 'avgTurnovers', 'estimatedPossessions', 'avgEstimatedPossessions', 'pointsPerEstimatedPossessions', 'threePointFieldGoalPct', 'twoPointFieldGoalsMade', 'twoPointFieldGoalsAttempted', 'avgTwoPointFieldGoalsMade', 'avgTwoPointFieldGoalsAttempted', 'twoPointFieldGoalPct', 'shootingEfficiency', 'scoringEfficiency', 'freeThrowPct', 'freeThrowsAttempted', 'freeThrowsMade', 'avgFreeThrowsMade', 'avgFreeThrowsAttempted', 'offensiveRebounds', 'avgOffensiveRebounds', 'offensiveReboundPct', 'totalTurnovers', 'avgTotalTurnovers', 'fastBreakPoints']
basketball_nba_defensive_stats = ['defensiveRebounds', 'avgDefensiveRebounds', 'turnoverPoints', 'steals', 'avgSteals', 'blocks', 'avgBlocks']

basketball_ncaab_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "defensiveRebounds",
  "avgDefensiveRebounds",
  "fouls",
  "rebounds",
  "avgRebounds",
  "totalRebounds",
  "gamesPlayed",
  "assists",
  "fieldGoals",
  "fieldGoalsAttempted",
  "fieldGoalsMade",
  "fieldGoalPct",
  "points",
  "threePointFieldGoalsAttempted",
  "avgFieldGoalsMade",
  "avgFieldGoalsAttempted",
  "avgThreePointFieldGoalsAttempted",
  "avgPoints",
  "avgAssists",
  "estimatedPossessions",
  "avgEstimatedPossessions",
  "pointsPerEstimatedPossessions",
  "twoPointFieldGoalsMade",
  "twoPointFieldGoalsAttempted",
  "avgTwoPointFieldGoalsMade",
  "avgTwoPointFieldGoalsAttempted",
  "twoPointFieldGoalPct",
  "shootingEfficiency",
  "scoringEfficiency",
  "assistTurnoverRatio",
  "turnovers",
  "totalTurnovers",
  "avgTurnovers",
  "avgTotalTurnovers",
  "freeThrowsAttempted",
  "avgFreeThrowsAttempted",
  "offensiveRebounds",
  "avgOffensiveRebounds",
  "offensiveReboundPct",
  "freeThrowPct",
  "freeThrowsMade",
  "avgFreeThrowsMade",
  "threePointFieldGoalsMade",
  "avgThreePointFieldGoalsMade",
  "threePointFieldGoalPct",
  "steals",
  "avgSteals",
  "stealFoulRatio",
  "stealTurnoverRatio",
  "turnoverPoints",
  "blocks",
  "avgBlocks",
  "blockFoulRatio",
  "fastBreakPoints"
]

basketball_ncaab_general_stats = ['fouls', 'avgFouls', 'rebounds', 'avgRebounds', 'totalRebounds', 'gamesPlayed', 'stealTurnoverRatio', 'blockFoulRatio']
basketball_ncaab_offensive_stats = ['assists', 'fieldGoals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalPct', 'points', 'threePointFieldGoalsAttempted', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgThreePointFieldGoalsAttempted', 'avgPoints', 'avgAssists', 'estimatedPossessions', 'avgEstimatedPossessions', 'pointsPerEstimatedPossessions', 'twoPointFieldGoalsMade', 'twoPointFieldGoalsAttempted', 'avgTwoPointFieldGoalsMade', 'avgTwoPointFieldGoalsAttempted', 'twoPointFieldGoalPct', 'shootingEfficiency', 'scoringEfficiency', 'assistTurnoverRatio', 'turnovers', 'totalTurnovers', 'avgTurnovers', 'avgTotalTurnovers', 'freeThrowsAttempted', 'avgFreeThrowsAttempted', 'offensiveRebounds', 'avgOffensiveRebounds', 'offensiveReboundPct', 'freeThrowPct', 'freeThrowsMade', 'avgFreeThrowsMade', 'threePointFieldGoalsMade', 'avgThreePointFieldGoalsMade', 'threePointFieldGoalPct', 'fastBreakPoints']
basketball_ncaab_defensive_stats = ['defensiveRebounds', 'avgDefensiveRebounds', 'steals', 'avgSteals', 'stealFoulRatio', 'turnoverPoints', 'blocks', 'avgBlocks']

basketball_wncaab_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "defensiveRebounds",
  "avgDefensiveRebounds",
  "fouls",
  "rebounds",
  "avgRebounds",
  "avgFouls",
  "totalRebounds",
  "gamesPlayed",
  "fieldGoals",
  "fieldGoalsAttempted",
  "fieldGoalsMade",
  "fieldGoalPct",
  "points",
  "turnovers",
  "totalTurnovers",
  "avgFieldGoalsMade",
  "avgFieldGoalsAttempted",
  "avgPoints",
  "avgTurnovers",
  "estimatedPossessions",
  "avgEstimatedPossessions",
  "pointsPerEstimatedPossessions",
  "avgTotalTurnovers",
  "twoPointFieldGoalsMade",
  "twoPointFieldGoalsAttempted",
  "avgTwoPointFieldGoalsMade",
  "avgTwoPointFieldGoalsAttempted",
  "twoPointFieldGoalPct",
  "shootingEfficiency",
  "scoringEfficiency",
  "threePointFieldGoalsAttempted",
  "avgThreePointFieldGoalsAttempted",
  "assistTurnoverRatio",
  "assists",
  "avgAssists",
  "offensiveRebounds",
  "avgOffensiveRebounds",
  "offensiveReboundPct",
  "freeThrowsAttempted",
  "avgFreeThrowsAttempted",
  "freeThrowPct",
  "freeThrowsMade",
  "avgFreeThrowsMade",
  "steals",
  "avgSteals",
  "stealFoulRatio",
  "stealTurnoverRatio",
  "threePointFieldGoalsMade",
  "avgThreePointFieldGoalsMade",
  "threePointFieldGoalPct",
  "turnoverPoints",
  "blocks",
  "avgBlocks",
  "blockFoulRatio",
  "fastBreakPoints"
]

basketball_wncaab_general_stats = ['fouls', 'rebounds', 'avgRebounds', 'avgFouls', 'totalRebounds', 'gamesPlayed', 'assistTurnoverRatio', 'stealFoulRatio', 'stealTurnoverRatio']
basketball_wncaab_offensive_stats = ['fieldGoals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalPct', 'points', 'turnovers', 'totalTurnovers', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgPoints', 'avgTurnovers', 'estimatedPossessions', 'avgEstimatedPossessions', 'pointsPerEstimatedPossessions', 'avgTotalTurnovers', 'twoPointFieldGoalsMade', 'twoPointFieldGoalsAttempted', 'avgTwoPointFieldGoalsMade', 'avgTwoPointFieldGoalsAttempted', 'twoPointFieldGoalPct', 'shootingEfficiency', 'scoringEfficiency', 'threePointFieldGoalsAttempted', 'avgThreePointFieldGoalsAttempted', 'assists', 'avgAssists', 'offensiveRebounds', 'avgOffensiveRebounds', 'offensiveReboundPct', 'freeThrowsAttempted', 'avgFreeThrowsAttempted', 'freeThrowPct', 'freeThrowsMade', 'avgFreeThrowsMade', 'threePointFieldGoalsMade', 'avgThreePointFieldGoalsMade', 'threePointFieldGoalPct', 'fastBreakPoints']
basketball_wncaab_defensive_stats = ['defensiveRebounds', 'avgDefensiveRebounds', 'steals', 'avgSteals', 'turnoverPoints', 'blocks', 'avgBlocks', 'blockFoulRatio']

icehockey_nhl_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "shotsAgainst",
  "saves",
  "savePct",
  "blockedShots",
  "hits",
  "shifts",
  "shotsTotal",
  "shotsMissed",
  "pointsPerGame",
  "totalFaceOffs",
  "faceoffsWon",
  "faceoffsLost",
  "faceoffPercent",
  "shotsIn1stPeriod",
  "shotsIn2ndPeriod",
  "shotsIn3rdPeriod",
  "giveaways",
  "takeaways",
  "penalties",
  "penaltyMinutes",
  "timesShortHanded",
  "powerPlayOpportunities",
  "shotDifferential",
  "goalsAgainst",
  "points",
  "goals",
  "shootingPct",
  "penaltyKillPct",
  "assists",
  "goalDifferential",
  "PIMDifferential",
  "powerPlayAssists",
  "powerPlayGoalsAgainst",
  "powerPlayGoals",
  "powerPlayPct",
]

icehockey_nhl_general_stats = ['shifts', 'shotDifferential', 'goalDifferential']
icehockey_nhl_offensive_stats = ['shotsTotal', 'shotsMissed', 'pointsPerGame', 'totalFaceOffs', 'faceoffsWon', 'faceoffsLost', 'faceoffPercent', 'shotsIn1stPeriod', 'shotsIn2ndPeriod', 'shotsIn3rdPeriod', 'giveaways', 'points', 'goals', 'shootingPct', 'assists']
icehockey_nhl_defensive_stats = ['shotsAgainst', 'saves', 'savePct', 'blockedShots', 'hits', 'takeaways', 'goalsAgainst', 'powerPlayOpportunities', 'powerPlayAssists', 'powerPlayGoals', 'powerPlayPct']
icehockey_nhl_penalty_stats = ['penaltyMinutes', 'PIMDifferential', 'penaltyKillPct', 'powerPlayGoalsAgainst', 'timesShortHanded']

baseball_mlb_stats = [
  "seasonWinLoss",
  "homeWinLoss",
  "awayWinLoss",
  "pointDiff",
  "gamesPlayed",
  "strikeouts_pitching",
  "strikeouts_batting",
  "hits",
  "runs",
  "atBats",
  "pitches",
  "plateAppearances",
  "runsCreated",
  "runsCreatedPer27Outs",
  "pitchesPerPlateAppearance",
  "MLBRating",
  "groundBalls",
  "flyBalls",
  "battersFaced",
  "thirdInnings",
  "gamesStarted",
  "fullInnings",
  "innings",
  "groundToFlyRatio",
  "pitchesPerInning",
  "BIPA",
  "strikes",
  "putouts",
  "successfulChances",
  "totalChances",
  "fieldingPct",
  "onBasePct",
  "OPS",
  "patienceRatio",
  "opponentOnBasePct",
  "opponentOPS",
  "runnersLeftOnBase",
  "WHIP",
  "assists",
  "strikeoutsPerNineInnings",
  "batterRating",
  "totalBases",
  "avg",
  "slugAvg",
  "opponentTotalBases",
  "opponentAvg",
  "opponentSlugAvg",
  "walks",
  "RBIs",
  "doubles",
  "walksPerPlateAppearance",
  "walkToStrikeoutRatio",
  "strikeoutToWalkRatio",
  "runsProduced",
  "extraBaseHits",
  "isolatedPower",
  "earnedRuns",
  "ERA",
  "teamEarnedRuns",
  "pitchCount",
  "strikePitchRatio",
  "finishes",
  "pitchesAsStarter",
  "pitchesPerStart",
  "homeRuns",
  "outsOnField",
  "rangeFactor",
  "catcherThirdInningsPlayed",
  "runSupport",
  "runSupportAvg",
  "atBatsPerHomeRun",
  "stolenBases",
  "hitByPitch",
  "doublePlays",
  "inheritedRunners",
  "GIDPs",
  "losses",
  "wins",
  "winPct",
]

baseball_mlb_batting_stats = ['gamesPlayed', 'strikeouts_batting', 'hits', 'runs', 'atBats', 'plateAppearances', 'runsCreated', 'pitchesPerPlateAppearance', 'MLBRating', 'groundBalls_batting', 'flyBalls_batting', 'groundToFlyRatio_batting', 'BIPA', 'onBasePct', 'OPS', 'patienceRatio', 'runnersLeftOnBase', 'batterRating', 'totalBases', 'avg', 'slugAvg', 'walks_batting', 'RBIs', 'doubles', 'walksPerPlateAppearance', 'walkToStrikeoutRatio', 'runsProduced', 'extraBaseHits', 'isolatedPower', 'homeRuns', 'atBatsPerHomeRun', 'stolenBases', 'hitByPitch', 'GIDPs', 'runsCreatedPer27Outs']
baseball_mlb_pitching_stats = ['strikeouts_pitching', 'pitches', 'groundBalls', 'flyBalls', 'battersFaced', 'thirdInnings', 'gamesStarted', 'fullInnings', 'innings', 'groundToFlyRatio', 'pitchesPerInning', 'strikes', 'opponentOnBasePct', 'opponentOPS', 'WHIP', 'strikeoutsPerNineInnings', 'opponentTotalBases', 'opponentAvg', 'opponentSlugAvg', 'walks', 'strikeoutToWalkRatio', 'earnedRuns', 'ERA', 'teamEarnedRuns', 'pitchCount', 'strikePitchRatio', 'finishes', 'pitchesAsStarter', 'pitchesPerStart', 'homeRuns_pitching', 'runSupport', 'runSupportAvg', 'inheritedRunners', 'losses', 'wins', 'winPct']
baseball_mlb_fielding_stats = ['putouts', 'successfulChances', 'totalChances', 'fieldingPct', 'assists', 'outsOnField', 'rangeFactor', 'catcherThirdInningsPlayed', 'doublePlays']

stat_config_map = {
    "baseball_mlb": {
        "default": baseball_mlb_stats,
        "categories": {
            "batting": baseball_mlb_batting_stats,
            "pitching": baseball_mlb_pitching_stats,
            "fielding": baseball_mlb_fielding_stats
        }
    },
    "americanfootball_nfl": {
        "default": americanfootball_nfl_stats,
        "categories": {
            "general": americanfootball_nfl_general_stats,
            "passing": americanfootball_nfl_passing_stats,
            "rushing": americanfootball_nfl_rushing_stats,
            "receiving": americanfootball_nfl_receiving_stats,
            "special_teams": americanfootball_nfl_special_teams_stats,
            "defensive": americanfootball_nfl_defensive_stats,
            "miscellaneous":  americanfootball_nfl_miscellaneous_stats,
        }
    },
    "americanfootball_ncaaf": {
        "default": americanfootball_ncaaf_stats,
        "categories": {
            "general": americanfootball_ncaaf_general_stats,
            "passing": americanfootball_ncaaf_passing_stats,
            "rushing": americanfootball_ncaaf_rushing_stats,
            "receiving": americanfootball_ncaaf_receiving_stats,
            "special_teams": americanfootball_ncaaf_special_teams_stats,
            "defensive": americanfootball_ncaaf_defensive_stats,
            "miscellaneous":  americanfootball_ncaaf_miscellaneous_stats,
        }
    },
    "basketball_nba": {
        "default": basketball_nba_stats,
        "categories": {
            "offensive": basketball_nba_offensive_stats,
            "defensive": basketball_nba_defensive_stats,
            "general": basketball_nba_general_stats
        }
    },
    "basketball_ncaab": {
        "default": basketball_ncaab_stats,
        "categories": {
            "offensive": basketball_ncaab_offensive_stats,
            "defensive": basketball_ncaab_defensive_stats,
            "general": basketball_ncaab_general_stats
        }
    },
    "basketball_wncaab": {
        "default": basketball_wncaab_stats,
        "categories": {
            "offensive": basketball_wncaab_offensive_stats,
            "defensive": basketball_wncaab_defensive_stats,
            "general": basketball_wncaab_general_stats
        }
    },
    "icehockey_nhl": {
        "default": icehockey_nhl_stats,
        "categories": {
            "offensive": icehockey_nhl_offensive_stats,
            "defensive": icehockey_nhl_defensive_stats,
            "general": icehockey_nhl_general_stats,
            "penalty": icehockey_nhl_penalty_stats
        }
    }
}

reverse_comparison_stats = [
    "totalPenalties",          # more penalties = worse
    "totalPenaltyYards",       # more penalty yards = worse
    "yardsAllowed",            # defense: fewer yards allowed = better
    "punts",                   # punting often indicates bad offense
    "sackYardsLost",           # total yards lost due to sacks
    "fumbles",                 # turnovers are bad
    "pointsAllowed",           # fewer points given up = better
    "fouls",
    "avgFouls",
    "turnovers",
    "avgTurnovers",
    "totalTurnovers",
    "avgTotalTurnovers",
    "shotsAgainst",
    "shotsMissed",           # wasted shooting opportunities
    "giveaways",             # turnovers
    "penalties",             # more penalties = worse
    "penaltyMinutes",        # PIM is always bad when high
    "timesShortHanded",      # being shorthanded is bad
    "goalsAgainst",          # fewer goals allowed = better defense
    "powerPlayGoalsAgainst", # allowing PP goals = bad
    "strikeouts_batting",    # strikeouts by hitters = bad
    "opponentOnBasePct",     # opponent OBP = lower is better
    "opponentOPS",           # opponent OPS = lower is better
    "runnersLeftOnBase",     # leaving runners stranded = negative
    "WHIP",                  # walks + hits per inning = lower is better
    "opponentTotalBases",    # bases allowed to opponents = bad
    "opponentAvg",           # opponent batting avg = bad
    "opponentSlugAvg",       # opponent slugging = bad
    "earnedRuns",            # ER allowed = bad
    "ERA",                   # key pitching metric: lower is better
    "teamEarnedRuns",        # team ER allowed = bad
    "inheritedRunners",      # inherited runners allowed (bad for relievers)
    "GIDPs",                 # grounded into double plays = bad for offense
    "losses",                # losses = negative
]

ignored_stats=[
    "gamesPlayed",
    "totalDrives",
    "longRushing",
    "longReception",
    "longPassing",
    "longPunt",
    "longPuntReturn"
    "longKickReturn",
    "longFieldGoalMade",
    "ESPNWRRating",
    "ESPNRBRating",
    "ESPNQBRating",
    "NBARating",
    "shifts",
    "MLBRating",
]